title: Site

tabs:
  main: 
    label: Paintings
    columns: 
      - width: 1/2
        sections:
          current:
            type: pages
            parent: site.find('paintings')
            template: painting
            image: 
              cover: true


      - width: 1/2
        sections:
          series:
            type: pages
            parent: site.find('series')
            sortBy: year desc
            template: series
  
  pages: 
    label: All Pages
    sections: 
      info: 
        type: pages
        template: about
      art: 
        type: pages
        parent: site
        templates:
          - serieses
          - paintings
  home: 
    label: Home
    sections: 
      home: 
        type: fields
        fields: 
          banner:
            extends: sections/banner
            width: 1/2
            size: huge
            label: Banner Image
            image: 
              ratio: 16/9
          mobile:
            extends: sections/banner
            help: Cropped banner image for mobile
            label: Mobile
            width: 1/4
            image:
              ratio: 4/5
          
            

